services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    volumes:
      - ./configs:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    environment:
      - VIRTUAL_HOST=homeassistant.robertfent.com
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=homeassistant.robertfent.com
      - LETSENCRYPT_EMAIL=info@robertfent.com
    restart: unless-stopped
    networks:
      - nginxproxy
    # privileged: true
    # network_mode: host

networks:
  nginxproxy:
    external: true