services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: serfent
    container_name: tailscale
    env_file: .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./configs/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always
    network_mode: host