
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  shutdown_local_server: "ssh -i ~/.ssh/remote-login -o StrictHostKeychecking=no robot@100.78.154.44 'sudo shutdown -h now'"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.22.0.0/16 
